FROM eclipse-temurin:18-jre-alpine

RUN mkdir /opt/app

COPY target/app.jar /opt/app/app.jar

wORKDIR	/opt/app

ENV PROFILE=dev

EXPOSE 8080

ENTRYPOINT ["java", "-Dspring.profiles.active=${PROFILE}", "-jar", "app.jar"]